# Generated by Django 3.2.19 on 2024-01-14 19:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0006_alter_products_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image_2',
            field=models.CharField(default=django.utils.timezone.now, max_length=350),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='image_3',
            field=models.CharField(default=1.0, max_length=350),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='image_4',
            field=models.CharField(default=11, max_length=350),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='image_5',
            field=models.CharField(default=11, max_length=350),
            preserve_default=False,
        ),
    ]
