# Generated by Django 3.2.19 on 2024-01-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0007_auto_20240114_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='code_postal',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
