# Generated by Django 3.2.19 on 2024-01-27 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0008_order_code_postal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code_postal',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
