# Generated by Django 3.2.19 on 2024-01-28 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0010_order_calle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='calle',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='code_postal',
            field=models.CharField(max_length=10),
        ),
    ]
