# Generated by Django 3.2.19 on 2024-02-05 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0011_auto_20240127_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='num_interior',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
