# Generated by Django 3.2.19 on 2024-02-21 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0013_products_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='stripe_price_id',
            field=models.CharField(default=12323, max_length=500),
            preserve_default=False,
        ),
    ]
