# Generated by Django 3.2.19 on 2024-03-21 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0014_products_stripe_price_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='comparative_price',
            field=models.IntegerField(default=0),
        ),
    ]
