# Generated by Django 3.2.19 on 2024-05-01 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0016_auto_20240412_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='id_product',
        ),
        migrations.AddField(
            model_name='products',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
