# Generated by Django 4.2.6 on 2023-10-24 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='image',
        ),
        migrations.RemoveField(
            model_name='products',
            name='subimage',
        ),
        migrations.RemoveField(
            model_name='products',
            name='subimage2',
        ),
        migrations.RemoveField(
            model_name='products',
            name='subimage3',
        ),
        migrations.RemoveField(
            model_name='products',
            name='subimage4',
        ),
    ]
